### PR TITLE
Feature/sorting

### PR DESCRIPTION
**Pull request by MartijnBogaert**
OPH-65
OPH-84

Sorting the BPMN files works as expected, however sorting the BPMN elements does not. Could that have something to do with the fact that responses for these contain multiple types of elements from the domain, confusing the resources service?

### CODE REVIEW

**Comment by MartijnBogaert** [comment]
@nbittich do you understand the issue with the bpmn elements not being sorted correctly (see pr description)?

**Comment by nbittich** [comment]
@MartijnBogaert yes, I'll try it on Monday to see if we can do something about that. I think we may not be able to easily fix it, if I find a workaround I will for sure let you know

**Review by nbittich — APPROVED** [review]
@MartijnBogaert sorting on the rdf:type doesn't really make sense and as you mentioned it will be difficult since we can have many types linked to a resource.

Sorting on real classifications would make way more sense so hopefully this can land at some point, but for now I approve the PR as-is

**Comment by MartijnBogaert** [comment]
@nbittich That's allright! For me sorting on name also doesn't seem to work as expected. Do you get the same thing? And do you think it's fixable?

**Comment by nbittich** [comment]
@MartijnBogaert yeah it sorts weirdly idd!  there are three states for the sorting:

- `None`:

image

- `name`:

image

- `-name`:

image


For the latest one, I see a name starting with an  'A'  before another one that starts with a 'V':

image

Maybe check the readme for mu-cl-resource, is there something mentioning that?

**Comment by MartijnBogaert** [comment]
@nbittich I did two things:
- sorting is now done case insensitively, because that's where things went wrong in the first place apparently
- however, things weren't working correctly after that fix, so i just implemented this as well: when sorting on name, only elements are returned that have a name value, and indeed, these are sorted perfectly fine

**Comment by nbittich** [comment]
sounds like a good approach 👍🏼

**Pull request merged**
